/*
    PROGRAM: LIBRARY MANAGEMENT SYSTEM
    LEARNING OUTCOME: DATA STRUCTURES AND ALGORITHMS
    PROGRAMMER: ANDERSON FEBRIAN TP053792
    DATA STRUCTURES IMPLEMENTED: MULTI-DIMENSIONAL LINKED LIST (BOOK) and SINGLY LINKED LIST (PATRON)
*/

#ifndef MAIN
#define MAIN

#include "Menu.h"

int main()
{
    menu::Menu(1);
    return 0;
}

#endif